CREATE DATABASE IF NOT EXISTS appdb;

USE appdb;

CREATE TABLE IF NOT EXISTS items (
    id   INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100)
);

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'P@ssw0rd!';

GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';

FLUSH PRIVILEGES;
